[package]
name = "ibus-keysend"
version = "1.2.0"
authors = ["gemmarx <gemmarx@users.noreply.github.com>"]

[dependencies]
regex = "*"
rustc-serialize = "*"
docopt = "*"
dbus = { git = "https://github.com/gemmarx/dbus-rs", branch = "addffi/dbus_connection_open_private" }

