[package]
name = "ibus-keysend"
version = "1.1.0"
authors = ["gemmarx <gemmarx@users.noreply.github.com>"]

[dependencies]
dbus = { git = "https://github.com/gemmarx/dbus-rs", branch = "addffi/dbus_connection_open_private" }
docopt = "*"
rustc-serialize = "*"
regex = "*"

